apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-config
  namespace: springboot
data:
  OTEL_SERVICE_NAME: "springboot"
  SPLUNK_PROFILER_ENABLED: "true"
  SPLUNK_PROFILER_MEMORY_ENABLED: "true"
  SPLUNK_METRICS_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics"
