apiVersion: v1
kind: Secret
metadata:
  name: splunk-secret
  namespace: springboot
type: Opaque
stringData:
  # Replace with your actual Splunk Observability access token
  access-token: "aSRv0jKuZaSGn6WY2G3IZA"
